import ast
import json
import re

from google.adk.agents import LlmAgent
from pydantic import BaseModel

from post_generator.agent_core.sub_agents.product_extractors.prompt import PRODUCT_EXTRACTOR_PROMPT
from products.ProductRepository import ProductRepository


import json

def extract_products(db_category_output: str, user_id: int):
    """
    Extract products based on category output and user ID.

    Args:
        db_category_output: JSON string containing category information
        user_id: The user ID to filter products by
    """
    def clean_and_parse_json(markdown_json_str):
        cleaned = re.sub(r"^```json\s*|\s*```$", "", markdown_json_str.strip(), flags=re.MULTILINE)
        return json.loads(cleaned)
    categoriese = clean_and_parse_json(db_category_output)
    print("dazfbne:"+str(categoriese))
    pr = ProductRepository()
    print(f'User ID: {user_id}')
    if user_id is None:
        raise ValueError("User ID (u_output) not found in session state")
    products = pr.find_by_token_and_categories(user_id, categoriese['categories'])
    products_dict = [p.model_dump() for p in products]
    return json.dumps(products_dict, default=str)



product_extractor_agent = LlmAgent (
    name="product_extractor_agent",
    model="gemini-2.0-flash-001",
    instruction="""You're an agent in charge of extracting products from a list of category ids and a user_id.
    Use the extract_products tool with the db_category_output from the previous agent and the user_id from the session state variable u_output.
    The user_id parameter should be set to {u_output}.""",
    description=PRODUCT_EXTRACTOR_PROMPT,
    output_key="extracted_products_v2",
    tools=[extract_products]
)

product_formatter_agent = LlmAgent(
    name="product_formatter_agent",
    model="gemini-2.0-flash-001",

    instruction="You're an agent in charge of formatting the extracted products into a the provided json format template.",
    description="""
            You are a content generation agent tasked with creating engaging promotional content that highlights selected products to attract potential customers and drive purchases.
            
            You are provided with a list of extracted products under the variable {extracted_products_v2}, generated by the product_extractor_agent. Each product includes attributes such as name, price, description, and media.
            
            Your task:
            Write a persuasive main marketing message that grabs attention, encourages customer inte.imageUrlrest, and promotes purchasing behavior. The tone should be enthusiastic, customer-focused, and sales-oriented.
            
            For each product, write a short personalized media message that:
            
            Highlights key benefits or features.
            
            Is enticing and concise.
            
            Encourages clicks or further interest.
            
            And don't forget to include the product name and price and id of the product.
            
            Final Output Format:
            Return your message as a JSON object structured exactly like below. Replace placeholders with real values (using the product media and your generated message for each):
            
            [
                {
                  "platform":"facebook",
                  "mainMessage": "Your persuasive promotional message goes here.",
                  "mediaDetails": [
                    {
                      "imageUrl": "media for product 1",
                      "message": "Short engaging message for product 1"
                    },
                    {
                      "imageUrl": "media for product 2",
                      "message": "Short engaging message for product 2"
                    }
                    // ...and so on for each product
                  ]
                },...
            ]
            
            Available platforms are : facebook,instagram.(everything should be in lowercase) 
            Don't forget to include product name,SKU.For facebook you can do it on each media but for instagram it should be in the main message.
            Important:
            
            Focus on selling the products in a natural way.
            
            Use emotionally engaging language (e.g., “Don’t miss out!”, “Elevate your style”, “Limited-time offer!”).
            
            Avoid generic filler text. Make each message specific to the product.
            
            Ensure valid JSON structure in the final output.
            
    """,
    output_key = "formatted_products",

)