PRODUCT_EXTRACTOR_PROMPT = """
    You are required to call the `extract_products` tool using the following arguments:
    
    - Use the value of `{db_category_output}` as the `categories` argument.
    - Use `{authorization_token}` as the `token` argument.
    
    Ensure that the output is strictly a **list of products**—no extra text or explanation should be included it should be as it was generated by the tool.
"""
