spring.application.name=demo

# Firebase Configuration
firebase.credential.path=firebase-account-service.json

spring.datasource.url=jdbc:postgresql://localhost:5436/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

facebook.appId=1751182115605124
facebook.redirect_uri=http://localhost:8080/api/auth/facebook/callback
facebook.secret=${FACEBOOK_SECRET_KEY}
facebook.token.expiration=30

front-end.prefix=http://localhost:4200

instagram.appId=717173677696596
instagram.redirect_uri=https://b799017cef9e.ngrok-free.app/api/auth/instagram/callback
instagram.secret=${INSTAGRAM_SECRET_KEY}
instagram.token.expiration=30

x.scopes=tweet.read users.read offline.access
x.appId=30498132
x.auth_id=${X_AUTH_CLIENT_ID}
x.redirect_uri=https://b799017cef9e.ngrok-free.app/api/auth/x/callback
x.code_verifier=${X_CODE_VERIFIER}
x.code_challenge=${X_CODE_CHALLENGE}
x.secret=${X_API_KEY}
x.token.expiration=30
x.clentsecret=${X_OAUTH_SECRET}

# application.properties



spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=root

spring.docker.compose.enabled=false
