SE....,..spring.application.name=demo
pu
# .,..Firebase Configuration
firebase.credential.path=firebase-account-service.json

spring.datasource.url=jdbc:postgresql://localhost:5437/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

facebook.appId=3273806436099805
facebook.redirect_uri=https://87c1b053e853.ngrok-free.app/api/auth/facebook/callback
facebook.secret=${FACEBOOK_SECRET_KEY}
facebook.token.expiration=30

front-end.prefix=http://localhost:4200

instagram.appId=603679482521142
instagram.redirect_uri=https://87c1b053e853.ngrok-free.app/api/auth/instagram/callback
instagram.secret=${INSTAGRAM_SECRET_KEY}
instagram.token.expiration=30

x.scopes=tweet.read users.read offline.access tweet.write
x.appId=30498132
x.auth_id=${X_AUTH_CLIENT_ID}
x.redirect_uri=https://87c1b053e853.ngrok-free.app/api/auth/x/callback
x.code_verifier=${X_CODE_VERIFIER}
x.code_challenge=${X_CODE_CHALLENGE}
x.secret=${X_API_KEY}
x.token.expiration=30
x.clentsecret=${X_OAUTH_SECRET}

# application.properties
messenger.verify_token=${MESSENGER_WEBHOOK_TOKEN}

app.base-url=http://localhost:8080

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=root

spring.docker.compose.enabled=false

python.service.url=http://localhost:5000

# WhatsApp API Configuration
whatsapp.api.url=https://graph.facebook.com/v22.0
whatsapp.phone.number.id=${WHATSAPP_PHONE_NUMBER_ID}
whatsapp.business.account.id=${WHATSAPP_BUSINESS_ACCOUNT_ID}

whatsapp.token=${WHATSAPP_TOKEN}

mvola.consumer.key=${LITTLE_CHERRY_MVOLA_SANDBOX_CONSUMER_KEY}
mvola.consumer.secret=${LITTLE_CHERRY_MVOLA_SANDBOX_CONSUMER_SECRET}
mvola.baseUrl=https://devapi.mvola.mg
mvola.partnerName=LittleCherry
mvola.partnerMsisdn=0343500003